# Kafka
kafka.bootstrap.servers=localhost:9092
kafka.topic=test-topic
kafka.group.id=test-group
kafka.poll.duration.ms=1000

# Snowflake channel
snowflake.channel.name=TEST_CHANNEL
snowflake.database=TEST_DATABASE
snowflake.schema=TEST_SCHEMA
snowflake.table=CALL_DETAIL_RECORDS


# Path to Snowflake profile JSON (contains account, user, role, private key)
snowflake.profile.path=profile.json

# Consumer tuning
max.rows.per.append=100
consumer.thread.count=3
